import { useState, type FormEvent, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { Activity, ArrowRight, Building2, Check, ChevronRight, CirclePlay, CloudRain, Database, Factory, Gauge, Layers3, Network, Radar, RadioTower, Route, Satellite, ShieldCheck, Sparkles, Waves } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ProductMockup } from "./product-mockup";
import { SectionHeader } from "./shared";
import { cn } from "@/lib/utils";

export function Hero() {
  return <section className="dark-band topo-field relative min-h-[980px] overflow-hidden pb-24 pt-32 lg:min-h-[1120px]">
    <div className="pointer-events-none absolute inset-0 grid-field opacity-30"/><div className="section-shell relative z-10 text-center">
      <p className="eyebrow mb-7">Plataforma de inteligencia hidrológica</p>
      <h1 className="mx-auto max-w-6xl font-display text-[clamp(4rem,9vw,7rem)] font-medium leading-[.9] text-on-dark">Anticipa la inundación.<br/><span className="text-primary">Decide antes.</span></h1>
      <p className="mx-auto mt-8 max-w-3xl text-lg leading-8 text-on-dark/65 lg:text-xl">TARANIS combina datos hidrometeorológicos, modelización e inteligencia artificial para transformar información compleja en predicciones y alertas útiles para la toma de decisiones.</p>
      <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild variant="hero" size="xl"><Link to="/contacto">Solicitar una demo <ArrowRight/></Link></Button><Button asChild variant="glass" size="xl"><a href="#plataforma">Ver cómo funciona <ChevronRight/></a></Button></div>
      <p className="mt-5 text-sm text-on-dark/40">Inteligencia hidrológica para territorios más resilientes.</p>
      <div className="relative mx-auto mt-16 max-w-6xl [perspective:1800px]"><div className="absolute -inset-10 bg-primary/5 blur-3xl"/><ProductMockup className="relative origin-top rotate-x-[3deg] lg:scale-[1.02]"/></div>
    </div>
  </section>;
}

function FlowDiagram() { return <div className="mt-16 grid items-center gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]">{[
  [CloudRain,"Lluvia","Intensidad"],[Route,"Escorrentía","Respuesta"],[Activity,"Caudal","Evolución"],[ShieldCheck,"Riesgo","Decisión"]
].map(([Icon,label,sub],i)=><div className="contents" key={String(label)}><div className="reveal-up group rounded-2xl border border-border bg-card p-7"><Icon className="size-6 text-primary"/><p className="mt-8 font-display text-2xl">{String(label)}</p><p className="mt-1 text-sm text-muted-foreground">{String(sub)}</p><div className="mt-6 h-16 overflow-hidden"><svg viewBox="0 0 160 60" className="size-full" aria-hidden="true"><path d={i===0?"M0 10 L20 45 L40 18 L60 50 L80 20 L100 42 L120 12 L140 50 L160 25":i===1?"M0 38 C30 5 45 50 75 25 S125 45 160 8":i===2?"M0 48 C35 47 45 43 70 39 S95 30 115 16 S145 8 160 6":"M0 50 L40 48 L70 36 L100 32 L125 14 L160 10"} fill="none" stroke="var(--primary)" strokeWidth="2"/></svg></div></div>{i<3&&<ArrowRight className="mx-auto hidden size-5 text-primary md:block"/>}</div>)}</div> }

export function ProblemAndPipeline() { const stages=[
  ["01 · Datos",["AEMET y radar","Estaciones y SAIH","Copernicus","Cartografía territorial"]],
  ["02 · Inteligencia",["Modelos hidrológicos","Inteligencia artificial","LSTM","Análisis histórico"]],
  ["03 · Predicción",["Precipitación","Caudal","Evolución temporal","Escenarios"]],
  ["04 · Decisión",["Mapas","Alertas","Indicadores","Seguimiento territorial"]]
]; return <>
  <section className="section-space bg-background"><div className="section-shell"><SectionHeader eyebrow="El reto" title={<>Cuando llega la inundación,<br/>cada minuto cuenta.</>} text="Los fenómenos extremos evolucionan rápidamente y las decisiones deben tomarse antes de que el impacto sea visible sobre el territorio."/><div className="mt-16 flex flex-wrap gap-x-8 gap-y-3 border-y border-border py-8 font-display text-[clamp(2rem,6vw,5rem)] font-medium text-surface-strong"><span className="reveal-up text-primary">DETECTAR</span><span className="reveal-up">ANTICIPAR</span><span className="reveal-up text-foreground">ACTUAR</span></div><FlowDiagram/></div></section>
  <section className="section-space dark-band"><div className="section-shell"><SectionHeader dark eyebrow="Sistema TARANIS" title="Del dato a la decisión." text="Una cadena tecnológica completa convierte fuentes heterogéneas en información territorial que se puede interpretar y utilizar."/><div className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-on-dark/10 bg-on-dark/10 lg:grid-cols-4">{stages.map(([title,items],i)=><div key={String(title)} className="relative bg-deep p-7"><span className="text-xs text-primary">0{i+1}</span><h3 className="mt-10 font-display text-2xl">{String(title).split(" · ")[1]}</h3><ul className="mt-6 space-y-3 text-sm text-on-dark/55">{(items as string[]).map(x=><li className="flex gap-2" key={x}><span className="mt-2 size-1 rounded-full bg-primary"/>{x}</li>)}</ul>{i<3&&<ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-6 rounded-full bg-primary p-1 text-primary-foreground lg:block"/>}</div>)}</div></div></section>
  </> }

export function ProductSection() { const labels=["Predicción hidrológica","Seguimiento de estaciones","Precipitación","Caudales","Cartografía de riesgo","Análisis histórico","Modelos comparables","Información territorial"]; const [active,setActive]=useState(0); return <section id="plataforma" className="section-space overflow-hidden bg-surface"><div className="section-shell"><SectionHeader eyebrow="La plataforma" title={<>Todo el territorio.<br/>Una sola plataforma.</>} text="Explora variables, compara escenarios y sigue la evolución del territorio desde un espacio de trabajo unificado."/><div className="mt-14 grid gap-8 lg:grid-cols-[260px_1fr]"><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{labels.map((x,i)=><button type="button" key={x} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} className={cn("rounded-xl border px-4 py-3 text-left text-xs transition-all",active===i?"border-primary bg-accent text-accent-foreground":"border-border bg-card text-muted-foreground hover:border-primary/40")}>{x}</button>)}</div><div className="relative"><ProductMockup/><div className="pointer-events-none absolute right-[8%] top-[16%] rounded-lg border border-primary/40 bg-deep px-3 py-2 text-xs text-on-dark shadow-aqua">{labels[active]}</div></div></div></div></section> }

export function VideoDemo() { const [playing,setPlaying]=useState(false); return <section className="section-space dark-band"><div className="section-shell grid items-center gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeader dark eyebrow="Demo" title="TARANIS en acción" text="Descubre cómo TARANIS transforma datos hidrológicos y meteorológicos en información útil para anticipar escenarios de inundación."/><Button asChild variant="hero" size="lg" className="mt-8"><Link to="/contacto">Solicitar una demostración personalizada</Link></Button></div><div className="aspect-video overflow-hidden rounded-2xl border border-on-dark/10 bg-deep-soft shadow-product">{playing?<iframe className="size-full" src="https://www.youtube-nocookie.com/embed/1jOw4fw0Ph8?autoplay=1" title="TARANIS en acción" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setPlaying(true)} className="group relative size-full overflow-hidden" aria-label="Reproducir vídeo TARANIS"><img src="https://i.ytimg.com/vi/1jOw4fw0Ph8/maxresdefault.jpg" alt="Vista previa del vídeo TARANIS" loading="lazy" className="size-full object-cover opacity-60 transition duration-500 group-hover:scale-[1.02] group-hover:opacity-75"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-20 place-items-center rounded-full bg-primary text-primary-foreground shadow-aqua-lg"><CirclePlay className="size-9"/></span></span></button>}</div></div></section> }

const features=[
  ["PREDICCIÓN","Anticipa la evolución de variables hidrológicas mediante modelos físicos y de inteligencia artificial.",Activity,"lg:col-span-2"],
  ["MAPA TERRITORIAL","Visualiza cuencas, ríos, estaciones, municipios y áreas expuestas desde una única interfaz.",Layers3,""],
  ["DATOS MULTIFUENTE","Combina información meteorológica, hidrológica, geoespacial y satelital.",Database,""],
  ["IA + HIDROLOGÍA","Complementa modelos hidrológicos clásicos con técnicas avanzadas de inteligencia artificial.",Sparkles,"lg:col-span-2"],
  ["ANÁLISIS HISTÓRICO","Reconstruye episodios y analiza la respuesta del territorio.",Gauge,""],
  ["VISUALIZACIÓN","Hidrogramas, hietogramas, indicadores y mapas para facilitar la interpretación.",Radar,""],
  ["ALERTAS","Convierte las predicciones en información operativa para apoyar decisiones.",RadioTower,""],
  ["ESCALABILIDAD","Arquitectura diseñada para trabajar desde municipios hasta áreas territoriales extensas.",Network,""
]] as const;
export function Features() { return <section className="section-space bg-background"><div className="section-shell"><SectionHeader eyebrow="Capacidades" title="Inteligencia aplicada al territorio."/><div className="mt-14 grid auto-rows-[minmax(260px,auto)] gap-4 md:grid-cols-2 lg:grid-cols-4">{features.map(([title,text,Icon,span],i)=><article key={title} className={cn("group relative overflow-hidden rounded-2xl border border-border bg-card p-6 transition duration-300 hover:-translate-y-1 hover:border-primary/40",span)}><Icon className="size-6 text-primary"/><h3 className="mt-12 font-display text-xl">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">{text}</p><div className="absolute inset-x-6 bottom-5 h-12"><svg viewBox="0 0 220 50" className="size-full" aria-hidden="true"><path d={`M0 ${35-i%3*7} C40 ${8+i*3} 65 48 110 ${25-i} S175 ${12+i} 220 ${20+i*2}`} fill="none" stroke="var(--primary)" strokeWidth="1.5" opacity=".5"/><circle cx={130+i*8} cy={22+i%2*5} r="3" fill="var(--aqua)"/></svg></div></article>)}</div></div></section> }

const forecast=[{t:"AHORA",rain:22,flow:18,state:"Estable"},{t:"+6 h",rain:48,flow:31,state:"Seguimiento"},{t:"+12 h",rain:73,flow:54,state:"Vigilancia"},{t:"+24 h",rain:42,flow:81,state:"Atención"},{t:"+48 h",rain:16,flow:49,state:"Descenso"}];
export function Prediction() { const [step,setStep]=useState(2); const d=forecast[step]; return <section className="section-space dark-band topo-field"><div className="section-shell"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionHeader dark eyebrow="Predicción" title="No necesitas esperar a que el agua llegue." text="Observa cómo puede evolucionar el sistema antes de que el episodio alcance su máxima intensidad."/><span className="w-fit rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs text-primary">Demostración visual · datos ficticios</span></div><div className="mt-14 rounded-2xl border border-on-dark/10 bg-deep-soft/80 p-6 md:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div><div className="grid h-56 grid-cols-2 items-end gap-3 border-b border-on-dark/20 px-4">{[["Precipitación",d.rain],["Caudal",d.flow]].map(([x,v])=><div key={String(x)} className="flex h-full flex-col justify-end"><div className="rounded-t-xl bg-primary/70 transition-all duration-500" style={{height:`${Number(v)}%`}}/><p className="mt-3 text-center text-xs text-on-dark/50">{x}</p></div>)}</div><input type="range" min="0" max="4" value={step} onChange={e=>setStep(Number(e.target.value))} className="mt-10 w-full accent-primary" aria-label="Horizonte temporal de la demostración"/><div className="mt-3 flex justify-between text-xs text-on-dark/45">{forecast.map(x=><span key={x.t}>{x.t}</span>)}</div></div><div className="rounded-xl border border-on-dark/10 bg-deep p-6"><p className="text-xs uppercase tracking-[.14em] text-on-dark/40">Estado del territorio</p><p className="mt-4 font-display text-4xl text-primary">{d.state}</p><div className="mt-8 space-y-4">{[["Lluvia",d.rain],["Respuesta fluvial",d.flow]].map(([x,v])=><div key={String(x)}><div className="flex justify-between text-xs"><span>{x}</span><span>{v}%</span></div><div className="mt-2 h-1 rounded-full bg-on-dark/10"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{width:`${Number(v)}%`}}/></div></div>)}</div></div></div></div></div></section> }

export function SolutionsAndDifference() { const users=[[Building2,"ADMINISTRACIONES","Información territorial para planificación, prevención y gestión del riesgo."],[ShieldCheck,"PROTECCIÓN CIVIL","Información operativa para anticipar escenarios y apoyar la coordinación."],[Waves,"ORGANISMOS DE CUENCA","Seguimiento hidrológico y análisis territorial integrado."],[Factory,"INFRAESTRUCTURAS Y EMPRESAS","Evaluación y seguimiento del riesgo asociado a activos e infraestructuras."]] as const; return <>
  <section className="section-space bg-surface"><div className="section-shell"><SectionHeader eyebrow="Soluciones" title="Diseñado para quienes tienen que decidir."/><div className="mt-14 grid gap-4 md:grid-cols-2">{users.map(([Icon,t,d])=><article key={t} className="group rounded-2xl border border-border bg-card p-8 transition hover:border-primary/50"><div className="flex items-center justify-between"><Icon className="size-7 text-primary"/><ArrowRight className="size-5 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-primary"/></div><h3 className="mt-16 font-display text-2xl">{t}</h3><p className="mt-3 max-w-md leading-7 text-muted-foreground">{d}</p></article>)}</div></div></section>
  <section className="section-space bg-background"><div className="section-shell grid gap-14 lg:grid-cols-[1fr_1.1fr]"><SectionHeader eyebrow="Cobertura" title="Inteligencia territorial sin convertir el territorio en una red de sensores." text="TARANIS puede aprovechar fuentes existentes, modelización, satélite y cartografía para analizar áreas extensas. Es una arquitectura diferente y escalable, compatible con sensores cuando aportan valor."/><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-border p-6"><p className="eyebrow">Enfoque instrumentado</p><div className="my-10 grid grid-cols-5 gap-3">{Array.from({length:15}).map((_,i)=><RadioTower key={i} className="size-4 text-muted-foreground"/>)}</div><p className="text-sm text-muted-foreground">Instrumentación física concentrada sobre zonas concretas.</p></article><article className="rounded-2xl border border-primary/30 bg-accent p-6"><p className="eyebrow">Arquitectura TARANIS</p><div className="my-10 grid grid-cols-2 gap-3">{[Database,Satellite,Layers3,Sparkles].map((I,i)=><div key={i} className="grid h-12 place-items-center rounded-xl bg-card"><I className="size-5 text-primary"/></div>)}</div><p className="text-sm text-muted-foreground">Fuentes existentes + modelos + satélite + cartografía + IA.</p></article></div></div></section>
  </> }

export function TechnologyAndCases() { const layers=["Datos","Procesamiento","Modelos hidrológicos","Inteligencia artificial","Predicción","Visualización y decisión"]; const cases=["Alertas tempranas","Seguimiento de episodios","Planificación municipal","Evaluación de riesgo","Protección de infraestructuras","Análisis postevento","Planes de emergencia","Gestión territorial"]; return <>
  <section className="section-space dark-band grid-field"><div className="section-shell"><SectionHeader dark eyebrow="Tecnología" title="La tecnología detrás de la anticipación."/><div className="mx-auto mt-16 max-w-4xl">{layers.map((x,i)=><div key={x} className="group relative mb-3 flex items-center gap-6 rounded-xl border border-on-dark/10 bg-deep/80 p-5 transition hover:border-primary/40"><span className="grid size-10 shrink-0 place-items-center rounded-full border border-primary/30 text-xs text-primary">{i+1}</span><span className="font-display text-lg">{x}</span><div className="ml-auto flex gap-1">{Array.from({length:4}).map((_,j)=><span key={j} className="size-1.5 rounded-full bg-primary/50"/>)}</div>{i<5&&<span className="absolute -bottom-4 left-10 z-10 h-5 w-px bg-primary/50"/>}</div>)}</div></div></section>
  <section className="section-space bg-surface"><div className="section-shell"><SectionHeader eyebrow="Aplicaciones" title={<>Un territorio.<br/>Distintos escenarios.</>}/><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{cases.map((x,i)=><article key={x} className="group relative min-h-56 overflow-hidden bg-card p-6"><div className="absolute inset-0 topo-field opacity-0 transition group-hover:opacity-60"/><span className="relative text-xs text-primary">0{i+1}</span><h3 className="relative mt-24 font-display text-xl">{x}</h3></article>)}</div></div></section>
  </> }

export function DeliveryAndTrust() { const plans=[["ESENCIAL","Monitorización y contexto territorial"],["PROFESIONAL","Predicción, modelos y alertas"],["TERRITORIAL","Cobertura y operación a escala amplia"]]; return <>
  <section className="section-space bg-background"><div className="section-shell"><SectionHeader eyebrow="Implementación" title="De tu territorio a TARANIS." text="Cada despliegue puede adaptarse a las características hidrológicas y operativas del territorio."/><div className="mt-14 grid gap-4 lg:grid-cols-4">{["Análisis","Integración de datos","Configuración y modelización","Operación"].map((x,i)=><article key={x} className="border-t border-primary pt-5"><span className="text-xs text-primary">0{i+1}</span><h3 className="mt-8 font-display text-xl">{x}</h3></article>)}</div><Button asChild variant="quiet" size="lg" className="mt-10"><Link to="/contacto">Háblanos de tu territorio <ArrowRight/></Link></Button></div></section>
  <section className="section-space bg-surface"><div className="section-shell"><SectionHeader eyebrow="Modelo de servicio" title="Una configuración para cada escala." text="Las capacidades y cobertura se configuran según el territorio, fuentes de información, nivel de modelización y necesidades operativas."/><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.map(([t,d],i)=><article key={t} className={cn("rounded-2xl border p-8",i===1?"border-primary bg-deep text-on-dark shadow-product":"border-border bg-card")}><p className="eyebrow">{t}</p><p className={cn("mt-8 min-h-14",i===1?"text-on-dark/65":"text-muted-foreground")}>{d}</p><ul className="my-8 space-y-3 text-sm">{["Cobertura configurable","Integración multifunción","Acompañamiento técnico"].map(x=><li className="flex gap-2" key={x}><Check className="size-4 text-primary"/>{x}</li>)}</ul><Button asChild variant={i===1?"hero":"quiet"} className="w-full"><Link to="/contacto">Solicitar información</Link></Button></article>)}</div></div></section>
  <section className="section-space bg-background"><div className="section-shell"><div className="grid gap-12 lg:grid-cols-2"><SectionHeader eyebrow="Confianza" title="Espacio para alianzas que importan." text="Este espacio queda preparado para incorporar exclusivamente programas, colaboradores, clientes, certificaciones y proyectos autorizados por TARANIS."/><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{["Programas","Colaboradores","Partners","Clientes","Certificaciones","Proyectos"].map(x=><div key={x} className="grid min-h-28 place-items-center rounded-xl border border-dashed border-border bg-surface text-xs text-muted-foreground">{x}</div>)}</div></div><div className="mt-20 grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-4">{[["24 h / 48 h","Horizontes según configuración"],["MULTIFUENTE","Integración de información"],["IA + HIDROLOGÍA","Modelización híbrida"],["TERRITORIAL","Arquitectura escalable"]].map(([a,b])=><div key={a} className="bg-card p-7"><p className="font-display text-2xl text-primary">{a}</p><p className="mt-2 text-sm text-muted-foreground">{b}</p></div>)}</div></div></section>
  </> }

export function ResourcesFaq() { const faqs=[
  ["¿Qué es TARANIS?","Una plataforma de inteligencia hidrológica y alerta temprana que integra datos, modelización e inteligencia artificial para apoyar decisiones."],
  ["¿Para qué territorios puede utilizarse?","Puede configurarse desde ámbitos municipales hasta áreas territoriales extensas, según datos y objetivos operativos."],
  ["¿Qué información utiliza TARANIS?","Información meteorológica, hidrológica, satelital, cartográfica e histórica, incluyendo fuentes como AEMET, radar, SAIH y Copernicus."],
  ["¿Es necesario instalar sensores?","No necesariamente. Puede aprovechar fuentes existentes y modelización, e integrar sensores cuando aporten valor."],
  ["¿Qué horizonte de predicción ofrece?","Puede trabajar con horizontes de 24 y 48 horas según la configuración, fuentes y modelos disponibles."],
  ["¿Puede integrarse con sistemas existentes?","La arquitectura está concebida para integrar fuentes y sistemas existentes según las necesidades del despliegue."],
  ["¿TARANIS sustituye a los sistemas de emergencia existentes?","No. TARANIS aporta información para apoyar y complementar los procedimientos y sistemas operativos existentes."],
  ["¿Cómo se implementa?","Mediante análisis del territorio, integración de datos, configuración y modelización, y puesta en operación."],
  ["¿Cómo puedo solicitar una demostración?","Completa el formulario y el equipo preparará una conversación adaptada a las características de tu territorio."]
]; return <>
  <section className="section-space bg-surface"><div className="section-shell"><SectionHeader eyebrow="Recursos" title="Conocimiento para anticipar."/><div className="mt-14 grid gap-4 md:grid-cols-3">{[["Nota técnica","Datos que explican un territorio"],["Caso de uso","Del episodio a la planificación"],["Vídeo","La plataforma en operación"]].map(([tag,t],i)=><article key={t} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="topo-field h-48 bg-deep-soft p-5"><span className="rounded-full bg-primary/15 px-3 py-1 text-xs text-primary">{tag}</span></div><div className="p-6"><h3 className="font-display text-xl">{t}</h3><p className="mt-5 flex items-center gap-2 text-sm text-primary">Próximamente <ArrowRight className="size-4"/></p></div></article>)}</div></div></section>
  <section className="section-space bg-background"><div className="section-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeader eyebrow="FAQ" title="Preguntas frecuentes."/><Accordion type="single" collapsible className="border-t border-border">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger className="py-6 text-left font-display text-base hover:no-underline">{q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  </> }

export function FinalCta() { return <section className="section-space dark-band topo-field"><div className="section-shell text-center"><h2 className="mx-auto max-w-5xl font-display text-[clamp(3rem,7vw,6.5rem)] font-medium leading-[.95]">El riesgo no espera.<br/><span className="text-primary">Tu decisión tampoco debería.</span></h2><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-on-dark/65">Descubre cómo TARANIS puede ayudar a anticipar escenarios de inundación en tu territorio.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild variant="hero" size="xl"><Link to="/contacto">Solicitar una demo</Link></Button><Button asChild variant="glass" size="xl"><Link to="/contacto">Contactar con TARANIS</Link></Button></div></div></section> }

export function DemoForm() { const [sent,setSent]=useState(false); function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)} if(sent)return <div className="rounded-2xl border border-primary/30 bg-accent p-10" role="status"><Check className="size-8 text-primary"/><h3 className="mt-6 font-display text-3xl">Gracias.</h3><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Nuestro equipo se pondrá en contacto contigo para conocer las características de tu territorio y preparar una demostración.</p></div>; return <form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Nombre"><Input required name="nombre"/></Field><Field label="Apellidos"><Input required name="apellidos"/></Field><Field label="Organización"><Input required name="organizacion"/></Field><Field label="Cargo"><Input name="cargo"/></Field><Field label="Email"><Input required type="email" name="email"/></Field><Field label="Teléfono"><Input type="tel" name="telefono"/></Field><Field label="País"><Input name="pais"/></Field><Field label="Tipo de organización"><select name="tipo" required className="flex h-11 w-full rounded-xl border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"><option value="">Seleccionar</option><option>Administración</option><option>Protección Civil</option><option>Organismo de cuenca</option><option>Empresa / Infraestructura</option><option>Otro</option></select></Field><Field label="Territorio de interés" wide><Input name="territorio"/></Field><Field label="Mensaje" wide><Textarea name="mensaje" className="min-h-32"/></Field><label className="flex gap-3 text-sm text-muted-foreground sm:col-span-2"><input required type="checkbox" className="mt-1 size-4 accent-primary"/>He leído y acepto la política de privacidad y el tratamiento de datos para atender mi solicitud.</label><Button type="submit" variant="hero" size="lg" className="sm:col-span-2 sm:w-fit">Solicitar demostración <ArrowRight/></Button></form> }
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}) { return <label className={cn("space-y-2 text-sm font-medium",wide&&"sm:col-span-2")}><span>{label}</span>{children}</label> }

export function ContactSection() { return <section className="section-space bg-surface"><div className="section-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeader eyebrow="Solicitar demo" title="Hablemos de tu territorio." text="Cuéntanos el contexto operativo y prepararemos una demostración centrada en tus necesidades."/><DemoForm/></div></section> }